// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH2YBe536OQUkuH6Eg-OqqgKuhdS3n-Y8',
    appId: '1:204040021736:web:23645d279a0c7def2f4b5d',
    messagingSenderId: '204040021736',
    projectId: 'nursingmother-64709',
    authDomain: 'nursingmother-64709.firebaseapp.com',
    storageBucket: 'nursingmother-64709.appspot.com',
    measurementId: 'G-JXMRFQQRSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGEOk5oGYeAeHxOpbfTdQAE3M_Uu-qQKY',
    appId: '1:204040021736:android:dd18bc886f4ee7182f4b5d',
    messagingSenderId: '204040021736',
    projectId: 'nursingmother-64709',
    storageBucket: 'nursingmother-64709.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAIlj_uNsO6RtYU13Y0j4plBvFn9okksw',
    appId: '1:204040021736:ios:b584f74cbbd84fd92f4b5d',
    messagingSenderId: '204040021736',
    projectId: 'nursingmother-64709',
    storageBucket: 'nursingmother-64709.appspot.com',
    iosBundleId: 'com.example.nursingMotherMedicalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAIlj_uNsO6RtYU13Y0j4plBvFn9okksw',
    appId: '1:204040021736:ios:b584f74cbbd84fd92f4b5d',
    messagingSenderId: '204040021736',
    projectId: 'nursingmother-64709',
    storageBucket: 'nursingmother-64709.appspot.com',
    iosBundleId: 'com.example.nursingMotherMedicalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH2YBe536OQUkuH6Eg-OqqgKuhdS3n-Y8',
    appId: '1:204040021736:web:2fe2c5dee92f501a2f4b5d',
    messagingSenderId: '204040021736',
    projectId: 'nursingmother-64709',
    authDomain: 'nursingmother-64709.firebaseapp.com',
    storageBucket: 'nursingmother-64709.appspot.com',
    measurementId: 'G-43DZLRCKXE',
  );
}
